# This is a basic workflow to help you get started with Actions

name: Build xzp AOSP

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Prepare Build Environment
      - name: Prepare Java Environment
        run: |
          sudo apt-get update
          sudo apt-get install openjdk-11-jdk


      # Runs a set of commands using the runners shell
      - name: Prepare Android Build Environment
        run: |
          sudo apt-get install bison g++-multilib git gperf libxml2-utils make zlib1g-dev:i386 zip liblz4-tool libncurses5 libssl-dev bc flex
          mkdir ~/bin
          curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          export PATH=~/bin:$PATH
          mkdir ~/android
          cd ~/android
          repo init -u git://github.com/LineageOS/android.git -b lineage-18.1
          mkdir .repo/local_manifests
          echo "

  <?xml version="1.0" encoding="UTF-8"?>
  <manifest>
      <!-- SONY -->
      <project name="whatawurst/android_kernel_sony_msm8998" path="kernel/sony/msm8998" remote="github" revision="lineage-18.1" />
      <project name="whatawurst/android_device_sony_yoshino-common" path="device/sony/yoshino-common" remote="github" revision="lineage-18.1" />
      <project name="whatawurst/android_device_sony_maple_dsds" path="device/sony/maple_dsds" remote="github" revision="lineage-18.1" />

      <!-- Pinned blobs for poplar -->
      <project name="whatawurst/android_vendor_sony_maple_dsds" path="vendor/sony/maple_dsds" remote="github" revision="lineage-18.1" />
  </manifest>
">> roomservice.xml

        repo sync
        
        source build/envsetup.sh
        lunch lineage_maple_dsds-userdebug
        make -j8 bacon
          
